name: semantic-release

on:
  push:
    branches: [main]

permissions:
  contents: write
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: RELEASE_ENV
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
